services:
  db:
    build:
      context: ./MySQL
      dockerfile: Dockerfile
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./MySQL/data:/var/lib/mysql
    networks:
      - portafolio-network
    healthcheck:
      test: ["CMD", "mysql" ,"-u", "portafolio-user", "-pCVEfL3^9CjoRJ#db"]
      interval: 30s
      timeout: 10s
      retries: 5

  adminer:
    image : adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - portafolio-network

networks:
  portafolio-network:
    driver: bridge
    name : portafolio-network